- hosts: test
  tasks:
  - name: create ssh key directory
    file:
      path: "/home/ansiblesvc@test.local/.ssh"
      state: directory
  - name: create empty file for sshkey
    file:
      path: "/home/ansiblesvc@test.local/.ssh/authorized_keys"
      state: touch
  - name: " create an ansible  user account with a sshkey"
    ansible.builtin.user:
      name: ansibleuser1
      create_home: yes
      generate_ssh_key: yes
      state: present
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  - name: "Add ansiblesvc account to the sudoers file"
    become: yes
    lineinfile:
      path: /etc/sudoers
      line: "ansiblesvc ALL=(ALL) NOPASSWD: ALL"
      create: yes