- hosts: test
  tasks:
  - name: update the system
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: restart system to reboot to newest kernel
    reboot:
      msg: "This server will be rebooted as part of scheduled patching."
      pre_reboot_delay: 5
      post_reboot_delay: 10
      reboot_timeout: 600